#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -Iinclude
CFLAGS = -Wall -pipe -mthreads -fopenmp -D__GNUWIN32__ -D__WXMSW__ -DWXUSINGDLL -DwxUSE_UNICODE -DSQLITE_THREADSAFE=1 -DTHREADSAFE=1
RESINC = 
LIBDIR = -Llib
LIB = -ltensorflow -lllama -lssl -lcrypto -lcrypt32 -lws2_32
LDFLAGS = -mthreads -fopenmp

INC_DEBUG = $(INC) -Ilib\\gcc_dll\\mswud -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g -D__WXDEBUG__
RESINC_DEBUG = $(RESINC) -Ilib\\gcc_dll\\mswud
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -Llib\\gcc_dll
LIB_DEBUG = $(LIB) -lwxmsw32ud_core -lwxbase32ud -lwxpngd -lwxzlibd
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\WESTSeer.exe

INC_RELEASE = $(INC) -Ilib\\gcc_dll\\mswu -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC) -Ilib\\gcc_dll\\mswu
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -Llib\\gcc_dll
LIB_RELEASE = $(LIB) -lwxmsw32u_core -lwxbase32u -lwxpng -lwxzlib
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\WESTSeer.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\src\\OpenAlex.o $(OBJDIR_DEBUG)\\src\\NeuralNetworkConfig.o $(OBJDIR_DEBUG)\\src\\MetricModel.o $(OBJDIR_DEBUG)\\src\\Matcher.o $(OBJDIR_DEBUG)\\src\\LLMConfig.o $(OBJDIR_DEBUG)\\src\\GeneralConfig.o $(OBJDIR_DEBUG)\\src\\EmailValidator.o $(OBJDIR_DEBUG)\\src\\CandidateIdentification.o $(OBJDIR_DEBUG)\\src\\CallbackData.o $(OBJDIR_DEBUG)\\src\\BitermWeight.o $(OBJDIR_DEBUG)\\src\\BitermDf.o $(OBJDIR_DEBUG)\\src\\AbstractTask.o $(OBJDIR_DEBUG)\\src\\AbstractMatcher.o $(OBJDIR_DEBUG)\\resource.o $(OBJDIR_DEBUG)\\src\\sqlite3.o $(OBJDIR_DEBUG)\\src\\porter2_stemmer.o $(OBJDIR_DEBUG)\\src\\TopicIndentification.o $(OBJDIR_DEBUG)\\src\\TimeSeriesRegression.o $(OBJDIR_DEBUG)\\src\\TimeSeriesExtraction.o $(OBJDIR_DEBUG)\\src\\TermTfIrdf.o $(OBJDIR_DEBUG)\\src\\TermExtraction.o $(OBJDIR_DEBUG)\\src\\TFModel.o $(OBJDIR_DEBUG)\\src\\StringProcessing.o $(OBJDIR_DEBUG)\\src\\StopWords.o $(OBJDIR_DEBUG)\\src\\StopWordMatcher.o $(OBJDIR_DEBUG)\\src\\ResearchScope.o $(OBJDIR_DEBUG)\\src\\Publication.o $(OBJDIR_DEBUG)\\src\\ProgressReporter.o $(OBJDIR_DEBUG)\\src\\PredictionModel.o $(OBJDIR_DEBUG)\\WESTSeerMain.o $(OBJDIR_DEBUG)\\WESTSeerApp.o $(OBJDIR_DEBUG)\\SettingsDialog.o $(OBJDIR_DEBUG)\\SQLDialog.o $(OBJDIR_DEBUG)\\OpenAlexImportDialog.o $(OBJDIR_DEBUG)\\LogDialog.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\src\\OpenAlex.o $(OBJDIR_RELEASE)\\src\\NeuralNetworkConfig.o $(OBJDIR_RELEASE)\\src\\MetricModel.o $(OBJDIR_RELEASE)\\src\\Matcher.o $(OBJDIR_RELEASE)\\src\\LLMConfig.o $(OBJDIR_RELEASE)\\src\\GeneralConfig.o $(OBJDIR_RELEASE)\\src\\EmailValidator.o $(OBJDIR_RELEASE)\\src\\CandidateIdentification.o $(OBJDIR_RELEASE)\\src\\CallbackData.o $(OBJDIR_RELEASE)\\src\\BitermWeight.o $(OBJDIR_RELEASE)\\src\\BitermDf.o $(OBJDIR_RELEASE)\\src\\AbstractTask.o $(OBJDIR_RELEASE)\\src\\AbstractMatcher.o $(OBJDIR_RELEASE)\\resource.o $(OBJDIR_RELEASE)\\src\\sqlite3.o $(OBJDIR_RELEASE)\\src\\porter2_stemmer.o $(OBJDIR_RELEASE)\\src\\TopicIndentification.o $(OBJDIR_RELEASE)\\src\\TimeSeriesRegression.o $(OBJDIR_RELEASE)\\src\\TimeSeriesExtraction.o $(OBJDIR_RELEASE)\\src\\TermTfIrdf.o $(OBJDIR_RELEASE)\\src\\TermExtraction.o $(OBJDIR_RELEASE)\\src\\TFModel.o $(OBJDIR_RELEASE)\\src\\StringProcessing.o $(OBJDIR_RELEASE)\\src\\StopWords.o $(OBJDIR_RELEASE)\\src\\StopWordMatcher.o $(OBJDIR_RELEASE)\\src\\ResearchScope.o $(OBJDIR_RELEASE)\\src\\Publication.o $(OBJDIR_RELEASE)\\src\\ProgressReporter.o $(OBJDIR_RELEASE)\\src\\PredictionModel.o $(OBJDIR_RELEASE)\\WESTSeerMain.o $(OBJDIR_RELEASE)\\WESTSeerApp.o $(OBJDIR_RELEASE)\\SettingsDialog.o $(OBJDIR_RELEASE)\\SQLDialog.o $(OBJDIR_RELEASE)\\OpenAlexImportDialog.o $(OBJDIR_RELEASE)\\LogDialog.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug:
	cmd /c echo done

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) -mwindows $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\src\\OpenAlex.o: src\\OpenAlex.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\OpenAlex.cpp -o $(OBJDIR_DEBUG)\\src\\OpenAlex.o

$(OBJDIR_DEBUG)\\src\\NeuralNetworkConfig.o: src\\NeuralNetworkConfig.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\NeuralNetworkConfig.cpp -o $(OBJDIR_DEBUG)\\src\\NeuralNetworkConfig.o

$(OBJDIR_DEBUG)\\src\\MetricModel.o: src\\MetricModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\MetricModel.cpp -o $(OBJDIR_DEBUG)\\src\\MetricModel.o

$(OBJDIR_DEBUG)\\src\\Matcher.o: src\\Matcher.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Matcher.cpp -o $(OBJDIR_DEBUG)\\src\\Matcher.o

$(OBJDIR_DEBUG)\\src\\LLMConfig.o: src\\LLMConfig.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\LLMConfig.cpp -o $(OBJDIR_DEBUG)\\src\\LLMConfig.o

$(OBJDIR_DEBUG)\\src\\GeneralConfig.o: src\\GeneralConfig.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\GeneralConfig.cpp -o $(OBJDIR_DEBUG)\\src\\GeneralConfig.o

$(OBJDIR_DEBUG)\\src\\EmailValidator.o: src\\EmailValidator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\EmailValidator.cpp -o $(OBJDIR_DEBUG)\\src\\EmailValidator.o

$(OBJDIR_DEBUG)\\src\\CandidateIdentification.o: src\\CandidateIdentification.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\CandidateIdentification.cpp -o $(OBJDIR_DEBUG)\\src\\CandidateIdentification.o

$(OBJDIR_DEBUG)\\src\\CallbackData.o: src\\CallbackData.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\CallbackData.cpp -o $(OBJDIR_DEBUG)\\src\\CallbackData.o

$(OBJDIR_DEBUG)\\src\\BitermWeight.o: src\\BitermWeight.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\BitermWeight.cpp -o $(OBJDIR_DEBUG)\\src\\BitermWeight.o

$(OBJDIR_DEBUG)\\src\\BitermDf.o: src\\BitermDf.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\BitermDf.cpp -o $(OBJDIR_DEBUG)\\src\\BitermDf.o

$(OBJDIR_DEBUG)\\src\\AbstractTask.o: src\\AbstractTask.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\AbstractTask.cpp -o $(OBJDIR_DEBUG)\\src\\AbstractTask.o

$(OBJDIR_DEBUG)\\src\\AbstractMatcher.o: src\\AbstractMatcher.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\AbstractMatcher.cpp -o $(OBJDIR_DEBUG)\\src\\AbstractMatcher.o

$(OBJDIR_DEBUG)\\resource.o: resource.rc
	$(WINDRES) -i resource.rc -J rc -o $(OBJDIR_DEBUG)\\resource.o -O coff $(INC_DEBUG)

$(OBJDIR_DEBUG)\\src\\sqlite3.o: src\\sqlite3.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\sqlite3.c -o $(OBJDIR_DEBUG)\\src\\sqlite3.o

$(OBJDIR_DEBUG)\\src\\porter2_stemmer.o: src\\porter2_stemmer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\porter2_stemmer.cpp -o $(OBJDIR_DEBUG)\\src\\porter2_stemmer.o

$(OBJDIR_DEBUG)\\src\\TopicIndentification.o: src\\TopicIndentification.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TopicIndentification.cpp -o $(OBJDIR_DEBUG)\\src\\TopicIndentification.o

$(OBJDIR_DEBUG)\\src\\TimeSeriesRegression.o: src\\TimeSeriesRegression.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TimeSeriesRegression.cpp -o $(OBJDIR_DEBUG)\\src\\TimeSeriesRegression.o

$(OBJDIR_DEBUG)\\src\\TimeSeriesExtraction.o: src\\TimeSeriesExtraction.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TimeSeriesExtraction.cpp -o $(OBJDIR_DEBUG)\\src\\TimeSeriesExtraction.o

$(OBJDIR_DEBUG)\\src\\TermTfIrdf.o: src\\TermTfIrdf.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TermTfIrdf.cpp -o $(OBJDIR_DEBUG)\\src\\TermTfIrdf.o

$(OBJDIR_DEBUG)\\src\\TermExtraction.o: src\\TermExtraction.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TermExtraction.cpp -o $(OBJDIR_DEBUG)\\src\\TermExtraction.o

$(OBJDIR_DEBUG)\\src\\TFModel.o: src\\TFModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\TFModel.cpp -o $(OBJDIR_DEBUG)\\src\\TFModel.o

$(OBJDIR_DEBUG)\\src\\StringProcessing.o: src\\StringProcessing.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\StringProcessing.cpp -o $(OBJDIR_DEBUG)\\src\\StringProcessing.o

$(OBJDIR_DEBUG)\\src\\StopWords.o: src\\StopWords.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\StopWords.cpp -o $(OBJDIR_DEBUG)\\src\\StopWords.o

$(OBJDIR_DEBUG)\\src\\StopWordMatcher.o: src\\StopWordMatcher.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\StopWordMatcher.cpp -o $(OBJDIR_DEBUG)\\src\\StopWordMatcher.o

$(OBJDIR_DEBUG)\\src\\ResearchScope.o: src\\ResearchScope.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\ResearchScope.cpp -o $(OBJDIR_DEBUG)\\src\\ResearchScope.o

$(OBJDIR_DEBUG)\\src\\Publication.o: src\\Publication.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Publication.cpp -o $(OBJDIR_DEBUG)\\src\\Publication.o

$(OBJDIR_DEBUG)\\src\\ProgressReporter.o: src\\ProgressReporter.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\ProgressReporter.cpp -o $(OBJDIR_DEBUG)\\src\\ProgressReporter.o

$(OBJDIR_DEBUG)\\src\\PredictionModel.o: src\\PredictionModel.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\PredictionModel.cpp -o $(OBJDIR_DEBUG)\\src\\PredictionModel.o

$(OBJDIR_DEBUG)\\WESTSeerMain.o: WESTSeerMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c WESTSeerMain.cpp -o $(OBJDIR_DEBUG)\\WESTSeerMain.o

$(OBJDIR_DEBUG)\\WESTSeerApp.o: WESTSeerApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c WESTSeerApp.cpp -o $(OBJDIR_DEBUG)\\WESTSeerApp.o

$(OBJDIR_DEBUG)\\SettingsDialog.o: SettingsDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SettingsDialog.cpp -o $(OBJDIR_DEBUG)\\SettingsDialog.o

$(OBJDIR_DEBUG)\\SQLDialog.o: SQLDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c SQLDialog.cpp -o $(OBJDIR_DEBUG)\\SQLDialog.o

$(OBJDIR_DEBUG)\\OpenAlexImportDialog.o: OpenAlexImportDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c OpenAlexImportDialog.cpp -o $(OBJDIR_DEBUG)\\OpenAlexImportDialog.o

$(OBJDIR_DEBUG)\\LogDialog.o: LogDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c LogDialog.cpp -o $(OBJDIR_DEBUG)\\LogDialog.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)\\src
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release:
	cmd /c echo done

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) -mwindows $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\OpenAlex.o: src\\OpenAlex.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\OpenAlex.cpp -o $(OBJDIR_RELEASE)\\src\\OpenAlex.o

$(OBJDIR_RELEASE)\\src\\NeuralNetworkConfig.o: src\\NeuralNetworkConfig.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\NeuralNetworkConfig.cpp -o $(OBJDIR_RELEASE)\\src\\NeuralNetworkConfig.o

$(OBJDIR_RELEASE)\\src\\MetricModel.o: src\\MetricModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\MetricModel.cpp -o $(OBJDIR_RELEASE)\\src\\MetricModel.o

$(OBJDIR_RELEASE)\\src\\Matcher.o: src\\Matcher.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Matcher.cpp -o $(OBJDIR_RELEASE)\\src\\Matcher.o

$(OBJDIR_RELEASE)\\src\\LLMConfig.o: src\\LLMConfig.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\LLMConfig.cpp -o $(OBJDIR_RELEASE)\\src\\LLMConfig.o

$(OBJDIR_RELEASE)\\src\\GeneralConfig.o: src\\GeneralConfig.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\GeneralConfig.cpp -o $(OBJDIR_RELEASE)\\src\\GeneralConfig.o

$(OBJDIR_RELEASE)\\src\\EmailValidator.o: src\\EmailValidator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\EmailValidator.cpp -o $(OBJDIR_RELEASE)\\src\\EmailValidator.o

$(OBJDIR_RELEASE)\\src\\CandidateIdentification.o: src\\CandidateIdentification.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\CandidateIdentification.cpp -o $(OBJDIR_RELEASE)\\src\\CandidateIdentification.o

$(OBJDIR_RELEASE)\\src\\CallbackData.o: src\\CallbackData.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\CallbackData.cpp -o $(OBJDIR_RELEASE)\\src\\CallbackData.o

$(OBJDIR_RELEASE)\\src\\BitermWeight.o: src\\BitermWeight.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\BitermWeight.cpp -o $(OBJDIR_RELEASE)\\src\\BitermWeight.o

$(OBJDIR_RELEASE)\\src\\BitermDf.o: src\\BitermDf.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\BitermDf.cpp -o $(OBJDIR_RELEASE)\\src\\BitermDf.o

$(OBJDIR_RELEASE)\\src\\AbstractTask.o: src\\AbstractTask.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\AbstractTask.cpp -o $(OBJDIR_RELEASE)\\src\\AbstractTask.o

$(OBJDIR_RELEASE)\\src\\AbstractMatcher.o: src\\AbstractMatcher.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\AbstractMatcher.cpp -o $(OBJDIR_RELEASE)\\src\\AbstractMatcher.o

$(OBJDIR_RELEASE)\\resource.o: resource.rc
	$(WINDRES) -i resource.rc -J rc -o $(OBJDIR_RELEASE)\\resource.o -O coff $(INC_RELEASE)

$(OBJDIR_RELEASE)\\src\\sqlite3.o: src\\sqlite3.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\sqlite3.c -o $(OBJDIR_RELEASE)\\src\\sqlite3.o

$(OBJDIR_RELEASE)\\src\\porter2_stemmer.o: src\\porter2_stemmer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\porter2_stemmer.cpp -o $(OBJDIR_RELEASE)\\src\\porter2_stemmer.o

$(OBJDIR_RELEASE)\\src\\TopicIndentification.o: src\\TopicIndentification.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TopicIndentification.cpp -o $(OBJDIR_RELEASE)\\src\\TopicIndentification.o

$(OBJDIR_RELEASE)\\src\\TimeSeriesRegression.o: src\\TimeSeriesRegression.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TimeSeriesRegression.cpp -o $(OBJDIR_RELEASE)\\src\\TimeSeriesRegression.o

$(OBJDIR_RELEASE)\\src\\TimeSeriesExtraction.o: src\\TimeSeriesExtraction.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TimeSeriesExtraction.cpp -o $(OBJDIR_RELEASE)\\src\\TimeSeriesExtraction.o

$(OBJDIR_RELEASE)\\src\\TermTfIrdf.o: src\\TermTfIrdf.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TermTfIrdf.cpp -o $(OBJDIR_RELEASE)\\src\\TermTfIrdf.o

$(OBJDIR_RELEASE)\\src\\TermExtraction.o: src\\TermExtraction.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TermExtraction.cpp -o $(OBJDIR_RELEASE)\\src\\TermExtraction.o

$(OBJDIR_RELEASE)\\src\\TFModel.o: src\\TFModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\TFModel.cpp -o $(OBJDIR_RELEASE)\\src\\TFModel.o

$(OBJDIR_RELEASE)\\src\\StringProcessing.o: src\\StringProcessing.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\StringProcessing.cpp -o $(OBJDIR_RELEASE)\\src\\StringProcessing.o

$(OBJDIR_RELEASE)\\src\\StopWords.o: src\\StopWords.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\StopWords.cpp -o $(OBJDIR_RELEASE)\\src\\StopWords.o

$(OBJDIR_RELEASE)\\src\\StopWordMatcher.o: src\\StopWordMatcher.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\StopWordMatcher.cpp -o $(OBJDIR_RELEASE)\\src\\StopWordMatcher.o

$(OBJDIR_RELEASE)\\src\\ResearchScope.o: src\\ResearchScope.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\ResearchScope.cpp -o $(OBJDIR_RELEASE)\\src\\ResearchScope.o

$(OBJDIR_RELEASE)\\src\\Publication.o: src\\Publication.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Publication.cpp -o $(OBJDIR_RELEASE)\\src\\Publication.o

$(OBJDIR_RELEASE)\\src\\ProgressReporter.o: src\\ProgressReporter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\ProgressReporter.cpp -o $(OBJDIR_RELEASE)\\src\\ProgressReporter.o

$(OBJDIR_RELEASE)\\src\\PredictionModel.o: src\\PredictionModel.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\PredictionModel.cpp -o $(OBJDIR_RELEASE)\\src\\PredictionModel.o

$(OBJDIR_RELEASE)\\WESTSeerMain.o: WESTSeerMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c WESTSeerMain.cpp -o $(OBJDIR_RELEASE)\\WESTSeerMain.o

$(OBJDIR_RELEASE)\\WESTSeerApp.o: WESTSeerApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c WESTSeerApp.cpp -o $(OBJDIR_RELEASE)\\WESTSeerApp.o

$(OBJDIR_RELEASE)\\SettingsDialog.o: SettingsDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SettingsDialog.cpp -o $(OBJDIR_RELEASE)\\SettingsDialog.o

$(OBJDIR_RELEASE)\\SQLDialog.o: SQLDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c SQLDialog.cpp -o $(OBJDIR_RELEASE)\\SQLDialog.o

$(OBJDIR_RELEASE)\\OpenAlexImportDialog.o: OpenAlexImportDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c OpenAlexImportDialog.cpp -o $(OBJDIR_RELEASE)\\OpenAlexImportDialog.o

$(OBJDIR_RELEASE)\\LogDialog.o: LogDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c LogDialog.cpp -o $(OBJDIR_RELEASE)\\LogDialog.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)\\src
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

